### ISSUE TITLE
VSS Phase-II Tracking issue

### ISSUE THREAD

**Issue by G8XSU** [lightningdevkit/vss-server#18]
**Phase-II:**  
Overall: Phase-II covers multi-device parallel usage, where a 2+ devices use the same lightning state machine and vss as primary storage for critical data. 
Ensuring sync b/w devices when one of them writes an update.  Ensuring data-integrating by preventing lightning state from getting corrupted using key-level & global-level versioning.
	
**VSS-Client Side :** 	
- [ ] PrimarySecondary KVStore Implementation
- [ ] Sync client-side acc. to server side changes and ListKeysSummary 
- [ ] Client-side impl for atomic multi-value filesystem-based store (possible required in SQLite if sled doesn't work for us)  
- [ ] LDK-Node integration for error handling on write failure and re-sync local view storage and retry.
- [ ] LDK Integration with additional error type on write. (has some unknowns)

**VSS-Server Side :**
- [x] Multi-tenanncy support - Create api to create storeId

**Comment by EthanYuan** [comment]
Hi, any chance for an update on this issue? Thanks!

**Comment by EthanYuan** [comment]
Yes, it is definitely worth learning from. [vss-rs](https://github.com/MutinyWallet/vss-rs) has also drawn from the VSS implementation. I understand that currently ldk-node has integrated the vss-client, but it hasn't fully utilized the version functionality yet (using -1). I'll keep an eye on future developments.
