### ISSUE TITLE
VSS Tracking Issue

### ISSUE THREAD

**Issue by G8XSU** [lightningdevkit/vss-server#9]
For background and an overview of the plan, see the LDK Roadmap.
This issue describes only execution plan specific to VSS.

**Phase-I:**
Overall: Phase-I covers single device usage, where a lightning node uses vss as primary storage for critical data(lightning state machine). 

Tasks: 
**VSS-Server Side :** 
- [x] Model/Interface design for VSS Service  (https://github.com/lightningdevkit/vss-server/pull/1), https://github.com/lightningdevkit/vss-server/pull/4)
- [x] Protobuf-generation setup for Server side ((https://github.com/lightningdevkit/vss-server/pull/5))
- [x] DB Schema 	((https://github.com/lightningdevkit/vss-server/pull/5))
- [x] Service setup (REST) for VSS (#4)
- [x] JOOQ generation setup for VSS-DB	((https://github.com/lightningdevkit/vss-server/pull/5))
- [x] Api Implementation for GetObject		(https://github.com/lightningdevkit/vss-server/pull/5)
- [x] Api Implementation for PutObject		(https://github.com/lightningdevkit/vss-server/pull/5)
- [x] Api Implementation for ListKeysVersions		(https://github.com/lightningdevkit/vss-server/pull/8)
- [x] Implement globalVersion/key-level concurrency checks for multi-device use in all of above API's (#5, #8)
- [x] Containerized Tests for Postgres implementation of Get, Put, ListKeyVersions and global/key-level versioning checks (https://github.com/lightningdevkit/vss-server/pull/6)
- [x] REST Controllers/ Api handlers for all the above api's (Depends on all of above) ( #10) (#12)
- [x] Dependency Injection Setup  (#11)	
- [x] Connection management and pooling for server (#11)
- [x] Testing (Basic testing done with just rust client-side, to do more testing after ldk-node integration)
- [x] Create Delete Api and add delete in tx support in write api (#15, https://github.com/lightningdevkit/vss-rust-client/pull/7)
- [x] Allow non-conditional put/delete operations (#17)
- [x] Docker support in vss-server (#32)
- [x] Usage Guide / Docs 

**VSS-Client Side** 

- [x] 	Protobuf-generation setup for Client side (rust)   (https://github.com/lightningdevkit/vss-rust-client/pull/2)
- [x]         Rust fmt and CI setup (https://github.com/lightningdevkit/vss-rust-client/pull/2)
- [x] 	 Basic HTTP thin client making calls to vss  		  (https://github.com/lightningdevkit/vss-rust-client/pull/1)	
- [x] 	 Tests for thin-client							   (https://github.com/lightningdevkit/vss-rust-client/pull/3)
- [x] 	 LDK-Node integration (Depends on LDK-Node Storage PR)  (https://github.com/lightningdevkit/ldk-node/pull/158)
- [x]   CI for ldk-node:vss integration
- [x] 	 Client-side encryption before storing objects in vss.  
- [x] 	 Document public methods in vss-client side.
- [x] Bindings support in ldk-node for build_with_vss_store
- [x] Dyn AuthMethod in vss-client
- [x] LnUrl Auth support in vss-client
- [x] Jwt authorizer support in vss-server
- [x] Usage Guide / Docs
